// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAllUsers(ctx context.Context) error
	DeleteChirp(ctx context.Context, id uuid.UUID) error
	GetChirp(ctx context.Context, id uuid.UUID) (Chirp, error)
	GetChirps(ctx context.Context) ([]Chirp, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserFromRefreshToken(ctx context.Context, token string) (uuid.UUID, error)
	RevokeRefreshToken(ctx context.Context, token string) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpgradeUserToChirpyRed(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
